name: dependencies
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  shimmer: ^1.1.2
  cached_network_image: ^2.4.1
  url_launcher: ^5.7.10
  flutter_launcher_icons: ^0.8.0
  package_info: ^0.4.3+2
  youtube_player_flutter: ^7.0.0+7
  flutter_svg: 0.19.0
  liquid_pull_to_refresh: ^2.0.0
  carousel_slider: ^2.3.1
  lottie: ^0.7.0+1
  fluttertoast: ^7.1.5

  # Core
  flutter_bloc: ^6.1.1
  shared_preferences: ^0.5.12+4
  equatable: ^1.2.5
  get_it: ^5.0.3
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
